### ISSUE TITLE
Cannot import grafx, modules are missing

### ISSUE THREAD

**Issue by p4thie** [sh-lee97/grafx#5]
## Description

Cannot import grafx because of missing modules, namely `torchaudio` and `scipy`.

## How to reproduce
1. Install grafx by running `pip install grafx` (or, `git clone https://github.com/sh-lee97/grafx` then `pip install -e .` )
2. `import grafx` via python REPL (for the sake of minimal reproduction)
3. `ModuleNotFoundError: No module named 'torchaudio'`. Even if you have `torchaudio` installed, `ModuleNotFoundError: No module named 'scipy'` gets raised.

## Expected behavior
Should be able to import `grafx` without manually resolving dependencies afterward.

## How to fix
-  For the temporary fix, after installing `grafx`, run `pip install torchaudio scipy`.
-  Add `torchaudio` and `scipy` in `pyproject.toml` to permanently resolve this (recommended).

## Environment
Python 3.10.12, Ubuntu 22.04

**Comment by p4thie** [comment]
Created draft pull request
https://github.com/sh-lee97/grafx/pull/6

**Comment by sh-lee97** [comment]
Oops, my bad. Sorry for the inconvenience and thanks for raising the issue! We approved your PR. 
We are working on the GitHub workflows to automatically test and detect such issues - we will finalize this asap.
